# Generated by Django 5.2.16 on 2026-08-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="retried",
            field=models.BooleanField(default=False),
        ),
    ]
