# Generated by Django 5.2.16 on 2026-08-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_retried"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvalRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("num_questions", models.IntegerField()),
                ("faithfulness_avg", models.FloatField()),
                ("context_precision_avg", models.FloatField()),
                ("per_question", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
