# Generated by Django 5.2.16 on 2026-08-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_evalrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="response_time_s",
            field=models.FloatField(default=0),
        ),
    ]
