# Generated by Django 5.2.17 on 2026-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_uploadrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="feedback",
            field=models.CharField(
                blank=True,
                choices=[("up", "Thumbs up"), ("down", "Thumbs down")],
                default="",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="source_details",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
