# Generated by Django 6.1 on 2026-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_feedback_message_source_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('domain', models.CharField(max_length=150)),
                ('citation_style', models.CharField(default='apa', max_length=4)),
                ('num_found', models.IntegerField(default=0)),
                ('num_ingested', models.IntegerField(default=0)),
                ('review_text', models.TextField(blank=True, default='')),
                ('papers', models.JSONField(blank=True, default=list)),
                ('bibliography', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
